-- AlterTable
ALTER TABLE "file" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL,
ALTER COLUMN "created_on" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "modified_on" SET DEFAULT CURRENT_TIMESTAMP;
